### ISSUE TITLE
ERROR collecting tests/test_fetches.py

### ISSUE THREAD

**Issue by drvpn** [c0lon/binance#2]
Hello,

I get the follow error when running setup.py test.  Any suggestions would be greatly appreciated!

root@arbitragi:/home/nickp/binance# python3 setup.py test
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'test_requires'
  warnings.warn(msg)
running pytest
running egg_info
writing binance.egg-info/PKG-INFO
writing dependency_links to binance.egg-info/dependency_links.txt
writing top-level names to binance.egg-info/top_level.txt
writing requirements to binance.egg-info/requires.txt
writing entry points to binance.egg-info/entry_points.txt
reading manifest file 'binance.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'binance.egg-info/SOURCES.txt'
running build_ext
========================================================================= test session starts ==========================================================================
platform linux -- Python 3.5.2, pytest-2.8.7, py-1.4.31, pluggy-0.3.1
rootdir: /home/nickp/binance, inifile: pytest.ini
collected 0 items / 1 errors 

================================================================================ ERRORS ================================================================================
________________________________________________________________ ERROR collecting tests/test_fetches.py ________________________________________________________________
/usr/lib/python3/dist-packages/_pytest/python.py:610: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python3/dist-packages/py/_path/local.py:650: in pyimport
    __import__(modname)
tests/__init__.py:3: in <module>
    from binance import (
binance/__init__.py:8: in <module>
    from .client import BinanceClient
E     File "/home/nickp/binance/binance/client.py", line 102
E       logger.info(f'{verb.upper()} {url}')
E                                         ^
E   SyntaxError: invalid syntax
======================================================================= 1 error in 0.16 seconds ========================================================================

**Comment by c0lon** [comment]
What version of python are you running? This module requires python >= 3.6.

**Comment by drvpn** [comment]
That must be it, I am on 2.7.12.

Thanks!
